function Participant10590degreecut06 = load_mot(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PARTICIPANT10590DEGREECUT06 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the numeric
%  data.
%
%  PARTICIPANT10590DEGREECUT06 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Participant10590degreecut06 = importfile("C:\Users\adpatrick\OneDrive - nih.no\Desktop\Calgary\Test2\Participant_105_90degreecut06.mot", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Sep-2023 13:55:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "ground_force_1_vx", "ground_force_1_vy", "ground_force_1_vz", "ground_force_1_px", "ground_force_1_py", "ground_force_1_pz", "ground_moment_1_mx", "ground_moment_1_my", "ground_moment_1_mz", "ground_force_2_vx", "ground_force_2_vy", "ground_force_2_vz", "ground_force_2_px", "ground_force_2_py", "ground_force_2_pz", "ground_moment_2_mx", "ground_moment_2_my", "ground_moment_2_mz"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ground_force_1_px", "ground_force_1_py", "ground_force_1_pz", "ground_moment_1_mx", "ground_moment_1_my", "ground_moment_1_mz", "ground_force_2_px", "ground_force_2_py", "ground_force_2_pz", "ground_moment_2_mx", "ground_moment_2_my", "ground_moment_2_mz"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["ground_force_1_px", "ground_force_1_py", "ground_force_1_pz", "ground_moment_1_mx", "ground_moment_1_my", "ground_moment_1_mz", "ground_force_2_px", "ground_force_2_py", "ground_force_2_pz", "ground_moment_2_mx", "ground_moment_2_my", "ground_moment_2_mz"], "ThousandsSeparator", ",");

% Import the data
Participant10590degreecut06 = readtable(filename, opts);

%% Convert to output type
Participant10590degreecut06 = table2array(Participant10590degreecut06);
end